services:
  h0neytr4p:
    build: .
    image: h0neytr4p:latest
    read_only: true
    container_name: h0neytr4p
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./log/:/opt/h0neytr4p/log/
      - ./payloads/:/opt/h0neytr4p/payloads/

